spring:
  application:
    name: rate-limiter-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      routes:
        - id: route1
          uri: ${SAMPLE_API_BASE_URL:http://localhost:8081}
          predicates:
            - Path=/tokenbucket/**
          filters:
            - name: CustomRateLimiter
              args:
                routeId: route1
            - StripPrefix=1

        - id: route2
          uri: ${SAMPLE_API_BASE_URL:http://localhost:8081}
          predicates:
            - Path=/leakybucket/**
          filters:
            - name: CustomRateLimiter
              args:
                routeId: route2
            - StripPrefix=1

        - id: slidingwindow
          uri: ${SAMPLE_API_BASE_URL:http://localhost:8081}
          predicates:
            - Path=/slidingwindow/**
          filters:
            - name: CustomRateLimiter
              args:
                routeId: slidingwindow
            - StripPrefix=1

        - id: slidingwindow-redis
          uri: ${SAMPLE_API_BASE_URL:http://localhost:8081}
          predicates:
            - Path=/slidingwindow-redis/**
          filters:
            - name: CustomRateLimiter
              args:
                routeId: slidingwindow-redis
            - StripPrefix=1

server:
  port: ${API_GATEWAY_RATELIMITER_PORT:8083}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

ratelimiter:
  sliding-window:
    limit: ${SLIDING_WINDOW_LIMIT:3}
    window-seconds: ${SLIDING_WINDOW_WINDOW_SECONDS:30}