events {}

http {
    upstream url_shortener_app {
        server url-shortener-1:8080;
        server url-shortener-2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://url_shortener_app;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
        }
    }
}
