events {}

http {
    upstream notification_service_app {
        server notification-service-1:8080;
        server notification-service-2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://notification_service_app;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
        }
    }
}
